[2025-02-14T06:21:32.776+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-14T06:21:32.791+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: web_to_snowflake.create_snowflake_table manual__2025-02-14T06:21:09.943985+00:00 [queued]>
[2025-02-14T06:21:32.800+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: web_to_snowflake.create_snowflake_table manual__2025-02-14T06:21:09.943985+00:00 [queued]>
[2025-02-14T06:21:32.800+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-14T06:21:32.810+0000] {taskinstance.py:2889} INFO - Executing <Task(SnowflakeOperator): create_snowflake_table> on 2025-02-14 06:21:09.943985+00:00
[2025-02-14T06:21:32.828+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=179) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-14T06:21:32.831+0000] {standard_task_runner.py:72} INFO - Started process 180 to run task
[2025-02-14T06:21:32.839+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'web_to_snowflake', 'create_snowflake_table', 'manual__2025-02-14T06:21:09.943985+00:00', '--job-id', '181', '--raw', '--subdir', 'DAGS_FOLDER/web_to_snowflake.py', '--cfg-path', '/tmp/tmpnz9xseh6']
[2025-02-14T06:21:32.847+0000] {standard_task_runner.py:105} INFO - Job 181: Subtask create_snowflake_table
[2025-02-14T06:21:32.944+0000] {task_command.py:467} INFO - Running <TaskInstance: web_to_snowflake.create_snowflake_table manual__2025-02-14T06:21:09.943985+00:00 [running]> on host 715f5b9093d1
[2025-02-14T06:21:33.041+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='web_to_snowflake' AIRFLOW_CTX_TASK_ID='create_snowflake_table' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T06:21:09.943985+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-14T06:21:09.943985+00:00'
[2025-02-14T06:21:33.044+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-14T06:21:33.062+0000] {sql.py:278} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS weather_table (
        temperature FLOAT,
        humidity FLOAT,
        date DATE,
        temperature_celsius FLOAT
    );
    
[2025-02-14T06:21:33.086+0000] {base.py:84} INFO - Retrieving connection 'snowflake_default'
[2025-02-14T06:21:33.097+0000] {base.py:84} INFO - Retrieving connection 'snowflake_default'
[2025-02-14T06:21:33.099+0000] {connection.py:414} INFO - Snowflake Connector for Python Version: 3.12.4, Python Version: 3.12.8, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.36
[2025-02-14T06:21:33.100+0000] {connection.py:1197} INFO - Connecting to GLOBAL Snowflake domain
[2025-02-14T06:21:33.101+0000] {connection.py:1278} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-02-14T06:21:33.806+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-02-14T06:21:33.808+0000] {sql.py:553} INFO - Running statement: CREATE TABLE IF NOT EXISTS weather_table (
        temperature FLOAT,
        humidity FLOAT,
        date DATE,
        temperature_celsius FLOAT
    );, parameters: None
[2025-02-14T06:21:33.920+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-02-14T06:21:33.920+0000] {sql.py:562} INFO - Rows affected: 1
[2025-02-14T06:21:33.921+0000] {snowflake.py:447} INFO - Rows affected: 1
[2025-02-14T06:21:33.921+0000] {snowflake.py:448} INFO - Snowflake query id: 01ba619d-3202-c6a3-0005-f9060003101a
[2025-02-14T06:21:33.987+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-02-14T06:21:33.988+0000] {connection.py:789} INFO - closed
[2025-02-14T06:21:34.035+0000] {connection.py:795} INFO - No async queries seem to be running, deleting session
[2025-02-14T06:21:34.131+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-14T06:21:34.132+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=web_to_snowflake, task_id=create_snowflake_table, run_id=manual__2025-02-14T06:21:09.943985+00:00, execution_date=20250214T062109, start_date=20250214T062132, end_date=20250214T062134
[2025-02-14T06:21:34.178+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-14T06:21:34.216+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-14T06:21:34.217+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
