[2025-02-14T17:03:20.379+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-14T17:03:20.392+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: web_to_snowflake.load_to_snowflake manual__2025-02-14T17:00:59.815624+00:00 [queued]>
[2025-02-14T17:03:20.402+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: web_to_snowflake.load_to_snowflake manual__2025-02-14T17:00:59.815624+00:00 [queued]>
[2025-02-14T17:03:20.403+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-14T17:03:20.415+0000] {taskinstance.py:2889} INFO - Executing <Task(SQLExecuteQueryOperator): load_to_snowflake> on 2025-02-14 17:00:59.815624+00:00
[2025-02-14T17:03:20.424+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2468) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-14T17:03:20.426+0000] {standard_task_runner.py:72} INFO - Started process 2469 to run task
[2025-02-14T17:03:20.428+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'web_to_snowflake', 'load_to_snowflake', 'manual__2025-02-14T17:00:59.815624+00:00', '--job-id', '208', '--raw', '--subdir', 'DAGS_FOLDER/web_to_snowflake.py', '--cfg-path', '/tmp/tmp8_wp71pw']
[2025-02-14T17:03:20.431+0000] {standard_task_runner.py:105} INFO - Job 208: Subtask load_to_snowflake
[2025-02-14T17:03:20.476+0000] {task_command.py:467} INFO - Running <TaskInstance: web_to_snowflake.load_to_snowflake manual__2025-02-14T17:00:59.815624+00:00 [running]> on host 715f5b9093d1
[2025-02-14T17:03:20.562+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='web_to_snowflake' AIRFLOW_CTX_TASK_ID='load_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T17:00:59.815624+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-14T17:00:59.815624+00:00'
[2025-02-14T17:03:20.564+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-14T17:03:20.578+0000] {sql.py:278} INFO - Executing: 
    COPY INTO sec_2016q4 (city, country, data, enddate, name, secquarter, startdate, symbol, secyear)
    FROM @my_s3_stage
        
    FILE_FORMAT = (TYPE = CSV)
    ON_ERROR = 'CONTINUE';
    
[2025-02-14T17:03:20.587+0000] {base.py:84} INFO - Retrieving connection 'snowflake_default'
[2025-02-14T17:03:20.599+0000] {base.py:84} INFO - Retrieving connection 'snowflake_default'
[2025-02-14T17:03:20.600+0000] {connection.py:414} INFO - Snowflake Connector for Python Version: 3.12.4, Python Version: 3.12.8, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.36
[2025-02-14T17:03:20.602+0000] {connection.py:1197} INFO - Connecting to GLOBAL Snowflake domain
[2025-02-14T17:03:20.602+0000] {connection.py:1278} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-02-14T17:03:21.081+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-02-14T17:03:21.082+0000] {sql.py:553} INFO - Running statement: COPY INTO sec_2016q4 (city, country, data, enddate, name, secquarter, startdate, symbol, secyear)
    FROM @my_s3_stage
        
    FILE_FORMAT = (TYPE = CSV)
    ON_ERROR = 'CONTINUE';, parameters: None
[2025-02-14T17:03:22.179+0000] {cursor.py:1166} INFO - Number of results in first chunk: 4
[2025-02-14T17:03:22.180+0000] {sql.py:562} INFO - Rows affected: 4
[2025-02-14T17:03:22.182+0000] {snowflake.py:447} INFO - Rows affected: 4
[2025-02-14T17:03:22.183+0000] {snowflake.py:448} INFO - Snowflake query id: 01ba641f-3202-c6a2-0005-f90600035026
[2025-02-14T17:03:22.404+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-02-14T17:03:22.405+0000] {connection.py:789} INFO - closed
[2025-02-14T17:03:22.476+0000] {connection.py:795} INFO - No async queries seem to be running, deleting session
[2025-02-14T17:03:22.551+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-14T17:03:22.551+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=web_to_snowflake, task_id=load_to_snowflake, run_id=manual__2025-02-14T17:00:59.815624+00:00, execution_date=20250214T170059, start_date=20250214T170320, end_date=20250214T170322
[2025-02-14T17:03:22.603+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-14T17:03:22.628+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-14T17:03:22.629+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
