[2025-02-14T06:21:19.121+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-14T06:21:19.136+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: web_to_snowflake.create_s3_stage manual__2025-02-14T06:21:09.943985+00:00 [queued]>
[2025-02-14T06:21:19.145+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: web_to_snowflake.create_s3_stage manual__2025-02-14T06:21:09.943985+00:00 [queued]>
[2025-02-14T06:21:19.145+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-14T06:21:19.156+0000] {taskinstance.py:2889} INFO - Executing <Task(SnowflakeOperator): create_s3_stage> on 2025-02-14 06:21:09.943985+00:00
[2025-02-14T06:21:19.165+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=165) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-14T06:21:19.167+0000] {standard_task_runner.py:72} INFO - Started process 166 to run task
[2025-02-14T06:21:19.168+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'web_to_snowflake', 'create_s3_stage', 'manual__2025-02-14T06:21:09.943985+00:00', '--job-id', '177', '--raw', '--subdir', 'DAGS_FOLDER/web_to_snowflake.py', '--cfg-path', '/tmp/tmpp5x3zgwu']
[2025-02-14T06:21:19.170+0000] {standard_task_runner.py:105} INFO - Job 177: Subtask create_s3_stage
[2025-02-14T06:21:19.206+0000] {task_command.py:467} INFO - Running <TaskInstance: web_to_snowflake.create_s3_stage manual__2025-02-14T06:21:09.943985+00:00 [running]> on host 715f5b9093d1
[2025-02-14T06:21:19.304+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='web_to_snowflake' AIRFLOW_CTX_TASK_ID='create_s3_stage' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T06:21:09.943985+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-14T06:21:09.943985+00:00'
[2025-02-14T06:21:19.306+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-14T06:21:19.320+0000] {sql.py:278} INFO - Executing: 
    CREATE STAGE IF NOT EXISTS my_s3_stage
    URL='s3://assignment2bigdatasystemss/weather/raw/'
    CREDENTIALS=(AWS_KEY_ID='AKIASVLKCUHQ7EZY6ZKW'
                AWS_SECRET_KEY='***');
    
[2025-02-14T06:21:19.327+0000] {base.py:84} INFO - Retrieving connection 'snowflake_default'
[2025-02-14T06:21:19.333+0000] {base.py:84} INFO - Retrieving connection 'snowflake_default'
[2025-02-14T06:21:19.334+0000] {connection.py:414} INFO - Snowflake Connector for Python Version: 3.12.4, Python Version: 3.12.8, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.36
[2025-02-14T06:21:19.335+0000] {connection.py:1197} INFO - Connecting to GLOBAL Snowflake domain
[2025-02-14T06:21:19.335+0000] {connection.py:1278} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-02-14T06:21:19.964+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-02-14T06:21:19.966+0000] {sql.py:553} INFO - Running statement: CREATE STAGE IF NOT EXISTS my_s3_stage
    URL='s3://assignment2bigdatasystemss/weather/raw/'
    CREDENTIALS=(AWS_KEY_ID='AKIASVLKCUHQ7EZY6ZKW'
                AWS_SECRET_KEY='***');, parameters: None
[2025-02-14T06:21:20.331+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-02-14T06:21:20.333+0000] {sql.py:562} INFO - Rows affected: 1
[2025-02-14T06:21:20.336+0000] {snowflake.py:447} INFO - Rows affected: 1
[2025-02-14T06:21:20.336+0000] {snowflake.py:448} INFO - Snowflake query id: 01ba619d-3202-c6a3-0005-f90600031012
[2025-02-14T06:21:20.436+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-02-14T06:21:20.438+0000] {connection.py:789} INFO - closed
[2025-02-14T06:21:20.488+0000] {connection.py:795} INFO - No async queries seem to be running, deleting session
[2025-02-14T06:21:20.583+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-14T06:21:20.583+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=web_to_snowflake, task_id=create_s3_stage, run_id=manual__2025-02-14T06:21:09.943985+00:00, execution_date=20250214T062109, start_date=20250214T062119, end_date=20250214T062120
[2025-02-14T06:21:20.643+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-14T06:21:20.690+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-14T06:21:20.692+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
