[2025-02-14T18:39:52.639+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-14T18:39:52.695+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: web_to_snowflake.transform_sec_data manual__2025-02-14T18:37:16.261867+00:00 [queued]>
[2025-02-14T18:39:52.707+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: web_to_snowflake.transform_sec_data manual__2025-02-14T18:37:16.261867+00:00 [queued]>
[2025-02-14T18:39:52.707+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-14T18:39:52.723+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform_sec_data> on 2025-02-14 18:37:16.261867+00:00
[2025-02-14T18:39:52.739+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3613) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-14T18:39:52.746+0000] {standard_task_runner.py:72} INFO - Started process 3621 to run task
[2025-02-14T18:39:52.741+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'web_to_snowflake', 'transform_sec_data', 'manual__2025-02-14T18:37:16.261867+00:00', '--job-id', '230', '--raw', '--subdir', 'DAGS_FOLDER/web_to_snowflake.py', '--cfg-path', '/tmp/tmpdql91j74']
[2025-02-14T18:39:52.757+0000] {standard_task_runner.py:105} INFO - Job 230: Subtask transform_sec_data
[2025-02-14T18:39:52.839+0000] {task_command.py:467} INFO - Running <TaskInstance: web_to_snowflake.transform_sec_data manual__2025-02-14T18:37:16.261867+00:00 [running]> on host 715f5b9093d1
[2025-02-14T18:39:52.941+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='web_to_snowflake' AIRFLOW_CTX_TASK_ID='transform_sec_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T18:37:16.261867+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-14T18:37:16.261867+00:00'
[2025-02-14T18:39:52.944+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-14T18:39:52.966+0000] {transform_sec_data.py:26} INFO - Processing  from 2016q4...
[2025-02-14T18:39:52.978+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-02-14T18:39:52.980+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-02-14T18:39:54.141+0000] {transform_sec_data.py:54} ERROR - Error processing file : An error occurred (404) when calling the HeadObject operation: Not Found
[2025-02-14T18:39:54.148+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-14T18:39:54.179+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-14T18:39:54.180+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=web_to_snowflake, task_id=transform_sec_data, run_id=manual__2025-02-14T18:37:16.261867+00:00, execution_date=20250214T183716, start_date=20250214T183952, end_date=20250214T183954
[2025-02-14T18:39:54.228+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-14T18:39:54.295+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-14T18:39:54.300+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
